enum ACTIONS {
  GET_ALL_POSTS = "GET_ALL_POSTS",
  CREATE_POST = "CREATE_POST",
  EDIT_POST = "EDIT_POST",
  DELETE_POST = "DELETE_POST",
  GET_ALL_COMMENTS = "GET_ALL_COMMENTS",
  CREATE_COMMENT = "CREATE_COMMENT",
  EDIT_COMMENT = "EDIT_COMMENT",
  DELETE_COMMENT = "DELETE_COMMENT",
  REQUEST_DATA = "REQUEST_DATA",
  RECEIVE_DATA = "RECEIVE_DATA",
  REJECT_DATA = "REJECT_DATA"
};

export default ACTIONS;